[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = 'source ~/.config/coc/coc-setting.vim'

[[plugins]]
repo = 'derekwyatt/vim-scala'

[[plugins]]
repo = 'vim-airline/vim-airline.git'
hook_add = '''
  let g:airline_theme='google_dark'
  let g:airline#extensions#tabline#enabled=1
  let g:airline_powerline_fonts=1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes.git'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'scrooloose/nerdtree'
