[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = 'source ~/.config/coc/coc-setting.vim'

[[plugins]]
repo = 'derekwyatt/vim-scala'

[[plugins]]
repo = 'vim-airline/vim-airline.git'

[[plugins]]
repo = 'vim-airline/vim-airline-themes.git'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'scrooloose/nerdtree'
